### ISSUE TITLE
Transactional guarantees with usage of socket timeouts?

### ISSUE THREAD

**Issue by ArwedSchmidt** [aerospike/aerospike-client-go#108]
Currently working on implementing a somewhat more complex type of queue, I took a look at how Aerospike itself and the Go-Client handle timeouts. I noticed that the client seems to set the socket timeout to policy.timeout and wonder how that might affect transactions of all kinds. 

I am basically worried that my call to `list.take_range()` will be atomically executed because it's still in time but the answer is never received by the client due to a socket timeout in the meantime. I would have lost the data. In other situations I might have my own retry-logic (more complex) that would perform an transaction twice if it's not protected with CAS.

Are you aware of this situation and would you see a way to decouple client network timeouts from server and client retry timeout? Or am I missing something? I think it would be far better if the server is responsible for termination (if it's designed to always send a timeout-reply). In the very rare case it fails to do so, I'd be ok with client blocking for more time than defined as timeout (e.g. 1 second on a 50ms server timeout).

My usecase requires a tight timeout in the average case and returns up to 100kb from the list.take_range op - that is a delay of 0.8ms at 1 Gbit/s or 8 ms at 0.1 Gbit/s - which makes this situation much more likely to occur than with artifically high timeouts. But high values for timeout wouldn't fully solve the issue anyways. However, I dont see any other way to achieve transactions with this without an additional roundtrip.

Relevant code is at aerospike-client-go/connection.go:setTimeout()

**Comment by bbulkow** [comment]
ArwedSchmidt, the problem of having a TCP connection failure which leaves the client not knowing the state of the database is a difficult one. It's also a problem for every database ( that connects over TCP, anyway ). The timeout case you mentioned is one of a class of cases like this, although the take() case is particularly interesting because - as you point out - data will be lost. Changing the timeout as you suggest reduces the timing window but does not eliminate the problem. Maybe that's good enough for you in the short term.

Aerospike is currently working toward solutions for this entire class of problems, and I would be interested in going over some of these designs with you. These solutions will not be done immediately but will be scheduled in the coming months. If you have the time and energy for a conversation, please contact me at brian@aerospike.com . Thanks.

**Comment by khaf** [comment]
Hi Brian,

I avoided to reply on the issue since I was waiting for Andy’s reply to my email to clarify the timeout semantics on server side.

This might be a trivial case or a complicated one depending how server acts on its queued pipeline. 

I will update you on how we progress on the issue.

Best,
K.

**Comment by khaf** [comment]
Since the operation you are interested in is not idempotent, you are right that setting a long timeout won't be a reliable solution to this problem. We need to decouple server and client timeouts.

We are having a discussion internally as to find the best solution for the problem. There are two main proposals:

1. Set the socket timeout longer than the operation timeout on client-side for non-idempotent operations. While this could help reduce the risk, it is not the correct solution IMO, since we still need a rather random algorithm to decide what the added delta T should be. If the server response still does not arrive on time to the client, data will be lost.

2. Set no timeout on the client and depend only on server timeout for non-idempotent operations. This is a better solution IMHO since it is formally correct and will move the consistency responsibility to the server, but comes with the risk of stale connections on client-side.

Thoughts?

**Comment by ArwedSchmidt** [comment]
(We worked around the issue for now, please don't prioritize changes or anything like that..)
Thoughts from my POV:

2) sounds better to me, but I'd put an upper limit on how long client additionally waits for server after timeout to avoid stale cons. A tunable value for WritePolicy maybe? E.g. would set that to 200ms while timeout is maybe 5ms. Users that favor SLA over correct responses, could set this to 0 (relative). Absolute settings help with simplicity:

```wPol.soft_timeout = 5```
```wPol.hard_timeout = 205```

Like Brian stated, any value would represent a trade-off (between correctness and worst-case latency). Docs/Knowledge base would need to state why hard TO should be > and not = to soft TO. Splitting returned error codes would help with operator awareness if ERR_UNSAFE_HARD_TIMEOUT occurs too often in log files / panics.
