### ISSUE TITLE
increment counter

### ISSUE THREAD

**Issue by foliodev** [aerospike/aerospike-client-go#12]
Hi,

I'd like to implement an incremental counter. 
What would be the fastest and most efficient way of doing this? Also, I would like to get the value of the bin once it is incremented. My concern is that I have to run 2 queries, 1 for updating the counter and one more for reading it. My worry is that with too many concurrent queries, there will be a gap between the update and read of the counter value. Hence giving an inaccurate value

Please advise.

Thanks

**Comment by artakvg** [comment]
@bbulkow  Is there any error/conflict handling mechanism or some other technique as to get guaranteed incremental counter even in concurrent queries or udf calls ?

This is something similiar to this from Stackoverflow 
http://stackoverflow.com/questions/25920610/aerospike-acid-clarification

**Comment by bbulkow** [comment]
As long as you have one cluster, these are serialized and there are no "race conditions", even in the case of concurrent queries and UDF calls.

Using datacenter replication is a different case, and we have a design for that. If so, you have an enterprise support license, so contact us.

In "split brain", where the network reaches a case where two parts of the cluster can't talk to each other, but both parts can talk to application servers, we err on the side of availability, so there are cases where the cluster splits, each side increments the same counter, and the merge will pick one over the other. We find these split brain cases really rare, because usually in split brain your application servers are split as well, and your load balancer can access one side and not the other... etc.

The only real solution to this kind of case ( " split brain " ) is to reduce availability - to stop reads and writes from minority sized clusters, or to use knowledge about counters which make them safer. In the case of counters, you have to generate a unique transaction ID and record it for a period of time, to avoid any form of "retry error". All of that means slower.

Are "split brain" network partitions the case you're worried about?
