### ISSUE TITLE
context support in aerospike client

### ISSUE THREAD

**Issue by clusc** [aerospike/aerospike-client-go#218]
Hi @khaf,

Recently we ran into some timeout issues when we suddenly lose a node. The client side latency shoot up, even though we have set a `basePolicy.Timeout = 500 * time.Miliseconds`. This is problematic because the go client doesn't accept context object, which we created with timeout. It would be good if we can support this to avoid such incident.

Thanks,

Eric

**Comment by khaf** [comment]
Hi @clusc,

I don't see how `context` would solve this problem. None of the `net` readers accept `context` as a parameter, so it is not possible to cancel the blocked connections. Wrapping the `context` would introduce unacceptable performance penalties.

As far as I can tell, the issue here is stale connections waiting for server response (which I don't know how that happens considering the server drops the connections altogether), during which a connection pool starvation happens.

I need clarification as to what do you exactly propose to to alleviate the issue.

**Comment by clusc** [comment]
My point being we'd like to have absolute control over client side timeout to prevent extreme high latency(during aerospike cluster migration for example). It's fine that we can't cancel the blocked connections(and even suffer connection pool starvation), but from our application perspective, we'd like to serve request in timely manner even if aerospike is misbehaving(we'd likely to send back partial response). That's our goal and why I proposed using `context` with timeout.

Having said that, I understand if we just wrap everything with context it will create extra latency. The other aspect of the question is why we will see +12s latency even though we've set a 500ms timeout on the base policy. Can you think of any scenario when the timeout is not honored? Could it be related to connection dial timeout which is longer?(In response to the issue we now also set the socket timeout to be the same value as transaction timeout, but not sure if it'd help).

**Comment by khaf** [comment]
I think it is the dialing that blocks, yes. And that can be managed by `context`, though I'm not sure how context would help in that regard.

I need some time to think how to solve this problem. It is not simply a problem of timeouts and pool starvation, but more a node life-cycle management.

**Comment by clusc** [comment]
How can we prevent the dialing timeout blocking issue in the short term? any existing parameter would help? I saw there's connection timeout, but the comment saying it's only for initial connection, does that also apply to the reconnect? This is very critical to our prod environment, so really appreciate your timely response.

**Comment by khaf** [comment]
At the moment, not much other than reducing that `timeout` value. When a node drops, it takes time (until next tend or a few) for the client to detect and drop that node. The first wave of transactions will timeout and return and the associated connections will be dropped from the pool.

The next wave will try to make new connections to the node, which will block on dial. Reducing that Dial timeout may help, but can also create other problems (like not being able to connect due to occasional DNS latency issues).

I have to fundamentally rethink this process to loosely decouple the connection dialing operation from the transaction pipeline to avoid this situation.

I already have some ideas which I'll explore during the coming week.

**Comment by clusc** [comment]
Ok just to confirm, what you're referring is the [`ClientPolicy.Timeout`](https://godoc.org/github.com/aerospike/aerospike-client-go#ClientPolicy) parameter, which will also be applied during reconnect, correct?

The latency increase we saw yesterday last around 8min, which is about the same time that the lost node come back online. That doesn't seem to match the tend interval which is by default 1s. Any other thoughts on why the lost node doesn't get detected by the client fast enough?

**Comment by khaf** [comment]
The node departures should be detected in at most 3 tends, which is 3 seconds. Anything else is either an exceptional situation or a bug we should hunt.

**Comment by clusc** [comment]
ok, we don't have enough data point to be confirmative on the exact outage time range, so will not create an issue with support. We will set the dial timeout to be a smaller number now to prevent outrageous latency during outage. We'll try to collect more data if same thing happens again, and we can discuss further. Keep us posted on the separation you mentioned above. Thanks a lot for helping.
