### ISSUE TITLE
client.Get() doesn't correctly report non existing record

### ISSUE THREAD

**Issue by marben** [aerospike/aerospike-client-go#232]
calling

`record, err := client.Get(nil, key, "binName")`

on non existing record results in both 'record' and 'err' being nil

I would expect to obtain error with ReturnCode() == types.KEY_NOT_FOUND_ERROR
which is what for instance a TouchOp does.

**Comment by khaf** [comment]
This is due to an unfortunate decision that was made 3 years ago when we were releasing the first iterations of the Go client.

While I agree with you, this is too big of a change to make since it can cause unexpected failures in production code.

It's a trivial change to make, I just need the community's consent before making it.

I invite everyone to weigh in on the proposal.

**Comment by khaf** [comment]
We'll address this issue in the future version 2.
