### ISSUE TITLE
Modules support

### ISSUE THREAD

**Issue by mariaefi29** [aerospike/aerospike-client-go#288]
Dear developers,

Could you please provide some information when you are planning to add modules dependency support?

Now we have to use vendor folder, because it pulls the wrong version of aerospike library after adding docker features in our app.

Would be very grateful for your reply.

**Comment by khaf** [comment]
I'm not sure when I'm going to do this, since it requires a new release workflow. At the moment we have two repos, one private, in which we do our experiments and testing. The public repo only reflects parts of the private one. Go modules will drastically change that, and I will have to update our release scripts and documentation to be able to support the Go modules.

No promises, but I'll see what I can do.

**Comment by mariaefi29** [comment]
Thank you @khaf!

**Comment by khaf** [comment]
Address via release of the v5.

**Comment by mariaefi29** [comment]
Thank you so much! Great news!
