### ISSUE TITLE
pkg.go.dev documentation is out-of-date

### ISSUE THREAD

**Issue by fillest** [aerospike/aerospike-client-go#321]
https://pkg.go.dev/github.com/aerospike/aerospike-client-go - "latest" is v1.39.0.
And https://godoc.org/github.com/aerospike/aerospike-client-go has a highlighted link to it in the page header.
From reading https://blog.golang.org/pkg.go.dev-2020 I have an impression that they are going to deprecate godoc.org

**Comment by khaf** [comment]
Thank you for reporting this problem.

Seems like this is due to their peculiar decisions regarding the Go modules and how new versions should be branched and the master to be freezed for v1.

I truly don't know what's the best course of action regarding this issue. Would invite feedback from our users to how to move forward.

**Comment by khaf** [comment]
Should be more or less resolved with the v5 release.
