### ISSUE TITLE
32bit support?

### ISSUE THREAD

**Issue by imkira** [aerospike/aerospike-client-go#33]
I have noticed aerospike-client-go does not build against x86 architectures.
The build fails with:

```
value.go:99: constant 9223372036854775807 overflows uint 
```

A simple attempt to fix the compilation error with:

```
-               if !Buffer.Arch64Bits || (val <= math.MaxInt64) {
+               if !Buffer.Arch64Bits || (uint64(val) <= uint64(math.MaxInt64)) {
```

and the compilation works but when I run the tests I get lots of failed tests.

I tried to fix some until I have just 9 out of 121 tests failing, but then when I look at the changes I have done and some parts of the code I don't quite understand I feel very uneasy about it such us:
- why no return instruction in PackObject inside `case uint` after `pckr.PackAULong(obj.(uint64))`
- why is the unpacker converting to uint32 something that was read as int32 but that you want as int64?

```
        case 0xce:
                val := uint32(Buffer.BytesToInt32(upckr.buffer, upckr.offset))
                upckr.offset += 4
                return int64(val), nil
```
- why does unpacker care about the current architecture when in fact it only accepts 64bit?

```
        case 0xce:
                val := uint32(Buffer.BytesToInt32(upckr.buffer, upckr.offset))
                upckr.offset += 4

               if Buffer.Arch64Bits {
                       return int(val), nil
               }
               return
```

And the list goes on.

**Comment by thomasmodeneis** [comment]
I've got same issue here, but im on macosx 64bits:
$ go get github.com/aerospike/aerospike-client-go
# github.com/aerospike/aerospike-client-go
/opt/gocode/src/github.com/aerospike/aerospike-client-go/value.go:99: constant 9223372036854775807 overflows uint

**Comment by khaf** [comment]
I'm also on MacOS X, and it compiles for me. Are you compiling for 64bits? What is your `$GOARCH`?

**Comment by birkirb** [comment]
:+1: Having this as an issue whith developers who are using i686 Linux distributions.

**Comment by khaf** [comment]
The reason I'm not really pushing hard on this issue is that even if I fix this problem (which is trivial to fix), the 32bit code will not run the same as 64bit code.

Unfortunately, I didn't plan for the client to be used on 32bit architectures, so on 64bit machines, all integers come back as `int` type (which is 64bits), while on 32bit machines, they should (and will) come back as `int64`.

What it implies is that the code written, tested and working on 64bit machines will panic on 32bit machines, and needs to be changed. e.g.:

```go
number := rec.Bins["IntBin"].(int)
```
has to change to:
```go
number := rec.Bins["IntBin"].(int64)
```
on 32bit machines.

The workaround is easy, but not elegant:
```go
func readInt64(rec *as.Record, binName string) int64 {
  val := rec.Bins[binName]
  if res, ok := val.(int); ok {
    return int64(res)
  }
  return val.(int64)
}
```

For many unsuspecting users, this will come as a surprise and will likely cause frustration.

If everyone here thinks that adding 32bit support with this caveat is a good compromise, I will fix the problem.

The right solution (making the integer numbers to return as `int64` on 64bit archs) is out of the question for current mainline version of the library, since it will break all existing code.

Thoughts?

**Comment by birkirb** [comment]
I can only speak for myself here, but the workaround is probably ok, in the sense that I generally avoid the int types and use the explicit ones. Also it's good in the sense that the onus will be on me to change my code rather than requiring all my devs to update their OSs. So I'd vote for the temp solution first and the right solution for the next version.

**Comment by imkira** [comment]
I am ok with that workaround too.

**Comment by kensully** [comment]
I am on Ubuntu 14.04 32 bit platform. Can not I compile it on x86?

**Comment by khaf** [comment]
This issue will be addressed in the future version 2.
