### ISSUE TITLE
Possible GC optimization for Value types

### ISSUE THREAD

**Issue by lming** [aerospike/aerospike-client-go#54]
I use UDF extensively and I found every call of Client.Execute() needs to call a couple NewXxxValue(), which wraps a type in a struct. For primitive types which used most often (by me :)), It seems using type alias can avoid the allocation of a new struct.

Present:
type BytesValue struct {
  bytes []byte
}

New:
type BytesValue []byte

Usually client code can do casting without call a new function. But we can still keep the new function for consistency and convenience:
func NewBytesValue(bytes []byte) BytesValue {
  return BytesValue(bytes)
}

func (b BytesValue) estimateSize() int {
  return len(b)
}

For List or Map, I am not in favor of adding a []byte to the ListValue struct and allocate the buffer and pack it at NewListValue(). I know it helps to estimate size of the final buffer so the final buffer can be allocated in one shot. But all these map, list values already allocated a buffer in order to achieve that. It seems maybe more efficient to let Go runtime to grow the buffer as needed, which very possibly involves less times of memory allocation. This is just my guess without profiling to support though :) I saw the reader() method uses the buffer but I think it's very easy to replace it with a WriteTo(io.Writer) method.

**Comment by khaf** [comment]
Type Alias is a neat trick! Hadn't thought of it. Will be in the next release.

Regarding pre-packing, I'm aware of the implications. I agree with you on principle.

The reason why it is implemented in this way is that all bin values are preceded by a header indicating their size. I haven't been able to come up with a clean solution that would not require an intermediate buffer. What this implies is that the buffer that returns the packed array cannot be the same as the final buffer, since we need the result first to write the header.

I also do not want to call the packer twice, once for size estimation, and once to write the result to the buffer.

Thoughts?

**Comment by lming** [comment]
What I can think of is to write the header with 0 as size first (if the size field is in fixed length), then pack the value and get the length, and then go back to change the size field in the header. Not very clean but may work.

**Comment by khaf** [comment]
The `Value` optimizations are in. Thanks for the tip.

I'll try to come up with a better solution for complex data types.

**Comment by lming** [comment]
Thanks for the improvements!

For NullValue, may want to avoid allocation (and avoid pointer) as well:
type NullValue struct{}
var nullValue NullValue
func NewNullValue() NullValue {
  return nullValue
}

**Comment by khaf** [comment]
Done.
