### ISSUE TITLE
Race condition during client authentication

### ISSUE THREAD

**Issue by imkira** [aerospike/aerospike-client-go#58]
The following sequence illustrates a possible race condition during client authentication.

https://github.com/aerospike/aerospike-client-go/blob/master/node.go#L223
https://github.com/aerospike/aerospike-client-go/blob/master/client.go#L1062
https://github.com/aerospike/aerospike-client-go/blob/master/cluster.go#L705-L710

I do not think changePassword should exist at all in cluster.go. Even if we protect the access to the password against race conditions, this will not propagate to other clients running in different processes/machines.
I understand this is a "utility" feature, but I think it should be the responsibility of the developers to reload the entire aerospike client.

**Comment by khaf** [comment]
Thanks for catching this, it can be a race condition and will be fixed in the next release. 

While it is true that this should be the responsibility of the user, we try our best to make the use of our client libraries as intuitive as possible for our newer users.

Distributed systems have a lot of surprises for new-comers, so helping them to get up to speed with the database and our clients is not a bad thing.

**Comment by khaf** [comment]
Fixed and In Master.
