### ISSUE TITLE
AerospikeError in main aerospike package

### ISSUE THREAD

**Issue by ErikDubbelboer** [aerospike/aerospike-client-go#77]
`AerospikeError` is now in the types package which requires an extra import (which I also rename since `types` is too generic to have as an import name) when you want to check the errors.

Shouldn't `AerospikeError` be in the main aerospike package including the error number definitions? Or aren't library users supposed to do anything with this struct?

**Comment by khaf** [comment]
I agree that in retrospect, we probably should have put it in the main package, but that's where it ended up and it is too late to move it since it will break a lot of working code.

The struct embeds the error interface, so it is compatible with error to pass around. Otherwise I fail to see what users would do with it.

**Comment by ErikDubbelboer** [comment]
We use it for:
```go
aerospikeErr.ResultCode() != aerospiketypes.TIMEOUT
```
Because we want to handle timeouts differently than other errors.

**Comment by khaf** [comment]
I normally do:

```go
import (
  as  "github.com/aerospike/aerospike-client-go"
  ast "github.com/aerospike/aerospike-client-go/types"
)
```

Looks explicit, and more concise.
